#!/usr/bin/env python3
"""Read the replies at each end of the persona-only PCA axes.

Same rows as pca_persona_only.py (6,821 persona replies, probe_l0 arm), layer 20, question-demeaned PCA. For each
slot and each of PC1-3, list the most extreme replies at both ends, at most 2 per question so no single question
fills a pole, with the judge's persona label, the regex family and the opening of the reply text.
Writes judge/pca_persona_poles.md (for reading) and judge/pca_persona_poles.json.
"""
import json, glob, re, argparse, pathlib
from collections import Counter
import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("--slots", default="R4,R8"); ap.add_argument("--layer", type=int, default=20)
ap.add_argument("--n", type=int, default=10); ap.add_argument("--chars", type=int, default=260)
a = ap.parse_args()
R = pathlib.Path(__file__).resolve().parents[2] / "results/brrrt"
meta = json.load(open(R / "hf_dl/features/features_meta.json")); LAYERS, SLOTS = meta["layers"], meta["slots"]
roll = meta["rollouts"]; gen = [json.loads(l) for l in open(R / "gen.jsonl")]
assert all((g["arm"], g["prompt_idx"], g["i"]) == (r["arm"], r["prompt_idx"], r["i"]) for g, r in zip(gen, roll))
p1 = json.load(open(R / "judge/judge_p1.json")); p2 = json.load(open(R / "judge/judge_p2.json"))
COT = re.compile(r"thinking aloud|internal monologue|stream of consciousness|inner monologue|thought process|reasoning aloud|self-talk|deliberat", re.I)
FAM = [("detective", r"detective|noir|sleuth|investigator"), ("chef", r"chef|cook|culinary|baker|foodie"),
       ("seafarer", r"captain|sailor|nautical|pirate|seafar"), ("poet", r"poet|lyric|verse|rhym|bard"),
       ("mystic", r"mystic|oracle|sage|spiritual|prophet|shaman|fortune"),
       ("mentor", r"mentor|coach|teacher|guide|advisor|counsel|instructor|tutor"),
       ("scholar", r"scientist|professor|scholar|historian|academic|researcher|philosoph"),
       ("aristocrat", r"gentleman|aristocrat|posh|sophisticated|butler|nobleman|victorian"),
       ("hype", r"hype|enthusiastic|energetic|excited|cheerleader|motivational|upbeat"),
       ("casual", r"casual|conversationalist|friend|buddy|slang|texter|chatty"),
       ("narrative", r"storytell|narrat|narrative|fiction|roleplay|character|script|drama|theatric")]
def fam(l):
    if not l or COT.search(l): return None
    for nme, pat in FAM:
        if re.search(pat, l, re.I): return nme
    return None
def is_cot(d): return bool(d["persona"]) and bool(COT.search(d.get("persona_label") or ""))
arm = np.array([r["arm"] for r in roll]); prompt = np.array([r["prompt_idx"] for r in roll])
persona = np.array([bool(x["persona"]) and bool(y["persona"]) and not (is_cot(x) or is_cot(y)) for x, y in zip(p1, p2)])
salad = np.array([x["coherent"] == 0 or y["coherent"] == 0 for x, y in zip(p1, p2)])
IP = np.flatnonzero((arm == "probe_l0") & ~salad & persona)
f1 = [fam(x.get("persona_label")) for x in p1]; f2 = [fam(y.get("persona_label")) for y in p2]

from transformers import AutoTokenizer
tok = AutoTokenizer.from_pretrained("Qwen/Qwen3-8B")
PROMPTS = {g["prompt_idx"]: g["prompt"] for g in gen}

SH = sorted(glob.glob(str(R / "hf_dl/features/X_*.npy"))); MM = [np.load(s, mmap_mode="r") for s in SH]
OFF = np.cumsum([0] + [m.shape[0] for m in MM])
def feat(L, s):
    li, si = LAYERS.index(L), SLOTS.index(s); out = np.empty((len(IP), MM[0].shape[3]), np.float32)
    for k, m in enumerate(MM):
        lo, hi = OFF[k], OFF[k + 1]; sel = IP[(IP >= lo) & (IP < hi)]
        if len(sel): out[np.searchsorted(IP, sel)] = np.asarray(m[sel - lo, li, si], np.float32)
    return out

def pick(order, n, cap=2):
    seen, out = Counter(), []
    for j in order:
        q = prompt[IP[j]]
        if seen[q] >= cap: continue
        seen[q] += 1; out.append(j)
        if len(out) == n: break
    return out
def item(j, z):
    r = IP[j]; txt = tok.decode(gen[r]["ids"], skip_special_tokens=True).replace("\n", " ⏎ ")
    return dict(row=int(r), score_sd=round(float(z), 2), question=PROMPTS[int(prompt[r])],
                label=p1[r].get("persona_label"), family=f1[r] if f1[r] == f2[r] else None,
                text=txt[:a.chars] + ("…" if len(txt) > a.chars else ""))

res, md = {}, ["# Replies at each end of the persona-only PCA axes",
               f"Layer {a.layer}, question-demeaned PCA on {len(IP)} persona replies. At most 2 replies per question per "
               "pole. Scores in SDs of the component. Generated by `code/brrrt/pca_persona_poles.py`.", ""]
g = prompt[IP]
for s in a.slots.split(","):
    X = feat(a.layer, s).astype(np.float64)
    for v in np.unique(g): X[g == v] -= X[g == v].mean(0)
    X -= X.mean(0); U, Sv, Vt = np.linalg.svd(X, full_matrices=False)
    Z = U[:, :3] * Sv[:3]; Z /= Z.std(0); var = Sv ** 2 / (Sv ** 2).sum()
    res[s] = {}
    md += [f"## After {s[1:]} reply tokens", ""]
    for i in range(3):
        z = Z[:, i]; o = np.argsort(z)
        lo = [item(j, z[j]) for j in pick(o, a.n)]; hi = [item(j, z[j]) for j in pick(o[::-1], a.n)]
        fl = Counter(f1[IP[j]] for j in o[: len(o) // 20] if f1[IP[j]]).most_common(4)
        fh = Counter(f1[IP[j]] for j in o[-(len(o) // 20):] if f1[IP[j]]).most_common(4)
        res[s][f"PC{i+1}"] = dict(var=round(float(var[i]), 4), low=lo, high=hi, low_families_top5pct=fl, high_families_top5pct=fh)
        md += [f"### PC{i+1} ({var[i]:.1%} of variance)", "",
               f"Families in the bottom 5%: {fl} · top 5%: {fh}", ""]
        for name, items in (("Low end", lo), ("High end", hi)):
            md += [f"**{name}**", ""]
            md += [f"- `{it['score_sd']:+.1f}` *{it['label']}* — Q: {it['question']}  \n  {it['text']}" for it in items]
            md += [""]
    print(f"{s}: done", flush=True)
json.dump(res, open(R / "judge/pca_persona_poles.json", "w"), indent=1)
open(R / "judge/pca_persona_poles.md", "w").write("\n".join(md)); print("->", R / "judge/pca_persona_poles.md")
